import { BeakerIcon,
    Bars3Icon,
    TrashIcon,
    AdjustmentsVerticalIcon,
    UserIcon,
    CakeIcon,
    ArrowTrendingUpIcon,
    FlagIcon,
    ShieldCheckIcon,
    TrophyIcon,
    CurrencyEuroIcon,
    HashtagIcon,
    ArrowsRightLeftIcon,
    EyeDropperIcon,
    GlobeAltIcon,
    LinkIcon,
    ArrowTrendingDownIcon,
    ScaleIcon,
    ChartBarIcon,
    SparklesIcon,
    CalendarIcon,
    QuestionMarkCircleIcon,
    ClockIcon,
    ArrowPathIcon,
    ArrowLeftIcon,
    ArrowUpIcon,
    HeartIcon,
    EyeIcon,
    InformationCircleIcon,
    XMarkIcon
} from '@heroicons/react/24/outline'
export const OutlineIcons = {
    BeakerIcon: BeakerIcon,
    TrashIcon: TrashIcon,
    Bars4Icon: Bars3Icon,
    AdjustmentsVerticalIcon: AdjustmentsVerticalIcon,
    GlobeAltIcon: GlobeAltIcon,
    UserIcon: UserIcon,
    CakeIcon: CakeIcon,
    ArrowTrendingUpIcon: ArrowTrendingUpIcon,
    FlagIcon: FlagIcon,
    ShieldCheckIcon: ShieldCheckIcon,
    TrophyIcon: TrophyIcon,
    HashtagIcon: HashtagIcon,
    ArrowsRightLeftIcon: ArrowsRightLeftIcon,
    EyeDropperIcon: EyeDropperIcon,
    LinkIcon: LinkIcon,
    ArrowTrendingDownIcon: ArrowTrendingDownIcon,
    ScaleIcon: ScaleIcon,
    ChartBarIcon: ChartBarIcon,
    SparklesIcon: SparklesIcon,
    CalendarIcon: CalendarIcon,
    CurrencyEuroIcon: CurrencyEuroIcon,
    QuestionMarkCircleIcon: QuestionMarkCircleIcon,
    ClockIcon: ClockIcon,
    ArrowPathIcon: ArrowPathIcon,
    ArrowLeftIcon:ArrowLeftIcon,
    ArrowUpIcon: ArrowUpIcon,
    HeartIcon: HeartIcon,
    EyeIcon: EyeIcon,
    InformationCircleIcon: InformationCircleIcon,
    XMarkIcon: XMarkIcon
}